export enum EstadoEvento {
  BORRADOR = 'BORRADOR',
  PUBLICADO = 'PUBLICADO',
  INSCRIPCIONES_ABIERTAS = 'INSCRIPCIONES_ABIERTAS',
  INSCRIPCIONES_CERRADAS = 'INSCRIPCIONES_CERRADAS',
  EN_CURSO = 'EN_CURSO',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
}